image: Visual Studio 2019
platform: x64
configuration: Release

shallow_clone: true

init: mkdir C:\projects\coinmp\Coinmp\MSVisualStudio\v16\x64\Release\


cache:
- C:\projects\coinmp\Cbc\
- C:\projects\coinmp\Clp\
- C:\projects\coinmp\Osi\
- C:\projects\coinmp\CoinUtils\
- C:\projects\coinmp\Cgl\



before_build:
- echo 'Collecting repos'
- git -C Cbc pull       || git clone --branch=master https://github.com/coin-or/Cbc
- git -C Clp pull       || git clone --branch=master https://github.com/coin-or/Clp
- git -C Osi pull       || git clone --branch=master https://github.com/coin-or/Osi
- git -C CoinUtils pull || git clone --branch=master https://github.com/coin-or/CoinUtils
- git -C Cgl pull       || git clone --branch=master https://github.com/coin-or/Cgl


build:
    

test:
    assemblies: 
       only:  
          - '**\x64\Release\UnitTestMSVS.dll'
