image: Visual Studio 2019
platform: x64
configuration: Release

shallow_clone: true

init:
- echo 'Collecting repos'
- git clone --branch=master https://github.com/coin-or/Cbc
- git clone --branch=master https://github.com/coin-or/Clp
- git clone --branch=master https://github.com/coin-or/Osi
- git clone --branch=master https://github.com/coin-or/CoinUtils
- git clone --branch=master https://github.com/coin-or/Cgl

before_build:


build:
    project: .\CoinMP\MSVisualStudio\v17\CoinMP.sln
