image: Visual Studio 2019
platform: x64
configuration: Release

shallow_clone: true

init:
- git clone --branch=master https://github.com/coin-or/Cbc
- git clone --branch=master https://github.com/coin-or/Clp
- git clone --branch=master https://github.com/coin-or/Cgl
- git clone --branch=master https://github.com/coin-or/Osi
- git clone --branch=master https://github.com/coin-or/CoinUtils

build:
    project: .\CoinMP\v10\MSVisualStudio\CoinMP.sln
