image: Visual Studio 2019
platform: x64
configuration: Release

shallow_clone: true

init:
- echo 'Collecting repos'
- git clone --branch=master https://github.com/coin-or/Cbc
- ls

before_build:
- ls

build:
    project: .\CoinMP\MSVisualStudio\v10\CoinMP.sln
